#!/usr/bin/env bash

main() {
  rm -r assets/images/scaled
  mkdir -p assets/images/scaled

  sizes=(200 800)

  for original in assets/images/original/*; do
    filename=$(basename -- "$original")
    extension="${filename##*.}"
    prefix="${filename%.*}"

    for size in "${sizes[@]}"; do
      scaled="assets/images/scaled/${prefix}_${size}.${extension}"
      scaled_webp="assets/images/scaled/${prefix}_${size}.webp"

      # Resize with original file type
      resize $size "$original" "$scaled"

      # Convert resized to webp
      cwebp \
        -quiet \
        -q 80 \
        "$scaled" \
        -o "$scaled_webp"
    done
  done
}

resize() {
    local size="$1"
    local in="$2"
    local out="$3"

    if command -v sips &> /dev/null; then
        sips "$in" \
          --resampleHeightWidthMax "$size" \
          --out "$out" > /dev/null

    elif command -v convert &> /dev/null; then
        convert "$in" \
          -resize "$size" \
          "$out"

    else
        echo "Error: Neither sips nor convert (ImageMagick) found." >&2
        return 1

    fi
}

main
